name: Deploy Backend DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.0 # Versão mais recente
        with:
          # Sugestão: Renomeie o secret para SERVER_SSH_PRIVATE_KEY para maior clareza
          ssh-private-key: ${{ secrets.MAMALOOMENU_GIT }}

      - name: Deploy no Servidor via SSH
        run: |
          ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e

            echo "=>  Acessando o diretório do projeto..."
            cd /home/mamaloomenu/devBackend-menuMamaloo/github/CustomMenu-Backend

            echo "=>  Atualizando para a versão mais recente do código..."
            git fetch origin main
            git reset --hard origin/main # Mais seguro para automação do que 'git pull'

            echo "=>  Recriando os contêineres com a nova versão..."
            docker-compose --env-file .env down --remove-orphans
            docker-compose --env-file .env up --build -d

            echo "=>  Limpando imagens Docker antigas..."
            docker image prune -af

            echo "Deploy finalizado com sucesso!"
          EOF